export enum Prioritaet {
  hoch = 'hoch',
  mittel = 'mittel',
  niedrig = 'niedrig',
}

export enum Status {
  entwurf = 'entwurf',
  aktiv = 'aktiv',
  inaktiv = 'inaktiv',
}

export enum AusbildungsnachweisStatus {
  entwurf = 'entwurf',
  eingereicht = 'eingereicht',
  in_pruefung = 'in_pruefung',
  visiert = 'visiert',
  archiviert = 'archiviert',
}

export enum SystemTyp {
  SAP = 'SAP',
  PERSONIO = 'PERSONIO',
  DATEV = 'DATEV',
  WORKDAY = 'WORKDAY',
  HR_WORKS = 'HR_WORKS',
}

export enum AusbildungsberufDto {
  systemintegration = 'systemintegration',
  anwendungsentwicklung = 'anwendungsentwicklung',
  daten_prozessanalyse = 'daten_prozessanalyse',
  digitale_vernetzung = 'digitale_vernetzung',
  fachinformatiker = 'fachinformatiker',
  elektroniker = 'elektroniker',
  industriemechaniker = 'industriemechaniker',
  mechatroniker = 'mechatroniker',
  zerspanungsmechaniker = 'zerspanungsmechaniker',
  konstruktionsmechaniker = 'konstruktionsmechaniker',
  werkzeugmechaniker = 'werkzeugmechaniker',
  automotive_mechaniker = 'automotive_mechaniker',
  kfz_mechaniker = 'kfz_mechaniker',
  landwirt = 'landwirt',
  forstwirt = 'forstwirt',
  gaertner = 'gaertner',
  tischler = 'tischler',
  steinmetz = 'steinmetz',
  maler = 'maler',
  glaser = 'glaser',
  sanitaer_heizung_klimatechnik = 'sanitaer_heizung_klimatechnik',
  elektronik_elektronik = 'elektronik_elektronik',
  IT_systemelektroniker = 'IT_systemelektroniker',
  pharmazeutisch_technischer_assistent = 'pharmazeutisch_technischer_assistent',
  medizinisch_technischer_assistent = 'medizinisch_technischer_assistent',
  biologo = 'biologe',
  chemielaborant = 'chemielaborant',
  lebensmittelchemiker = 'lebensmittelchemiker',
  lebensmitteltechnologe = 'lebensmitteltechnologe',
  banker = 'banker',
  kaufmann_fuer_bankwirtschaft = 'kaufmann_fuer_bankwirtschaft',
  kaufmann_fuer_spedition_logistik = 'kaufmann_fuer_spedition_logistik',
  kaufmann_fuer_marketingkommunikation = 'kaufmann_fuer_marketingkommunikation',
  kaufmann_fuer_digitalmanagement = 'kaufmann_fuer_digitalmanagement',
  kaufmann_fuer_versicherungen = 'kaufmann_fuer_versicherungen',
  industriekaufmann = 'industriekaufmann',
  bankkaufmann = 'bankkaufmann',
  sparkassenkaufmann = 'sparkassenkaufmann',
  steuerfachangestellter = 'steuerfachangestellter',
  steuerfachwirt = 'steuerfachwirt',
  wirtschaftspruefer = 'wirtschaftspruefer',
  controller = 'controller',
  bilanzbuchhalter = 'bilanzbuchhalter',
  personalreferent = 'personalreferent',
  personalkaufmann = 'personalkaufmann',
  vertriebskaufmann = 'vertriebskaufmann',
  kaufmann_fuer_einzelhandel = 'kaufmann_fuer_einzelhandel',
  kaufmann_fuer_spedition = 'kaufmann_fuer_spedition',
  kaufmann_fuer_lagerlogistik = 'kaufmann_fuer_lagerlogistik',
  kaufmann_fuer_marketing = 'kaufmann_fuer_marketing',
  kaufmann_fuer_digitalisierung = 'kaufmann_fuer_digitalisierung',
  kaufmann_fuer_cybersicherheit = 'kaufmann_fuer_cybersicherheit',
  kaufmann_fuer_kI = 'kaufmann_fuer_kI',
  kaufmann_fuer_data_science = 'kaufmann_fuer_data_science',
  kaufmann_fuer_webentwicklung = 'kaufmann_fuer_webentwicklung',
  kaufmann_fuer_gamedesign = 'kaufmann_fuer_gamedesign',
  kaufmann_fuer_medientechnik = 'kaufmann_fuer_medientechnik',
  kaufmann_fuer_fotografie = 'kaufmann_fuer_fotografie',
  kaufmann_fuer_video_produktion = 'kaufmann_fuer_video_produktion',
  kaufmann_fuer_audio_technik = 'kaufmann_fuer_audio_technik',
  kaufmann_fuer_tischlerei = 'kaufmann_fuer_tischlerei',
  kaufmann_fuer_metallgestaltung = 'kaufmann_fuer_metallgestaltung',
  kaufmann_fuer_glasgestaltung = 'kaufmann_fuer_glasgestaltung',
  kaufmann_fuer_keramik = 'kaufmann_fuer_keramik',
  kaufmann_fuer_textilgestaltung = 'kaufmann_fuer_textilgestaltung',
  kaufmann_fuer_goldschmied = 'kaufmann_fuer_goldschmied',
  kaufmann_fuer_juwelier = 'kaufmann_fuer_juwelier',
  kaufmann_fuer_pflege = 'kaufmann_fuer_pflege',
  kaufmann_fuer_ergotherapie = 'kaufmann_fuer_ergotherapie',
  kaufmann_fuer_physiotherapie = 'kaufmann_fuer_physiotherapie',
  kaufmann_fuer_logopaedie = 'kaufmann_fuer_logopaedie',
  kaufmann_fuer_heilerziehungspflege = 'kaufmann_fuer_heilerziehungspflege',
  kaufmann_fuer_soziale_pflege = 'kaufmann_fuer_soziale_pflege',
  kaufmann_fuer_altenpflege = 'kaufmann_fuer_altenpflege',
  kaufmann_fuer_krankenpflege = 'kaufmann_fuer_krankenpflege',
  kaufmann_fuer_pflegewissenschaften = 'kaufmann_fuer_pflegewissenschaften',
}
